### PR TITLE
Updates the Supply Since Merge Widget tooltip

### PR DESCRIPTION
**Pull request by ledbetterljoshua**
This PR updates the 'Supply Since Merge' widget tooltip to show the supply change percentage across time. 

This is something I'm personally interested in keeping track of. I'm creating this PR in case others are too.

### CODE REVIEW

**Comment by alextes** [comment]
Hah how cool @ledbetterljoshua . Definitely going to check this out. Thanks for creating a PR to add to the public good instead of keeping it for private use 🙏 .

**Comment by alextes** [comment]
photo_2022-10-24 18 21 01

I see, I like it. We might adapt it a little so the values stay right aligned but imo this can go in. I'll talk to the rest of the team 👍 .

**Comment by ledbetterljoshua** [comment]
Awesome! And yep that makes sense. I'm happy to contribute! I've been using this site for a while now and only just found out it's open source. Super impressed with the whole thing :)

**Comment by alextes** [comment]
@ledbetterljoshua the branch had a conflict, I tried to resolve it with GitHub but now I can't merge at all anymore. Can you rebase / merge the latest main, we'd like to merge it!

**Comment by alextes** [comment]
Silly me. A rebase and merge was out of my control but merging with a commit was perfectly possible. Slightly messier history, totally fine. Thanks again! You can expect to see it on the live site in the next 24h 🥳 .

**Comment by ledbetterljoshua** [comment]
Hey, sorry I didn't see your previous comment. I'm glad you figured it out though! And okay awesome, thank you! 🚀

**Pull request merged**
