### PR TITLE
fix(BurnCategories): Separators in Gauge, Contract Creation category, improved category names / labels

### PR DESCRIPTION
**Pull request by ckoopmann**
- [x] Add  Separators in gauge (closes: https://github.com/ultrasoundmoney/frontend/issues/300)
- [x] Add "Contract creation" category
- [x] Add examples for categories included in "misc"
- [x] Use better category names in leaderboard

### CODE REVIEW

**Comment by ckoopmann** [comment]
Before:
image

After: 
image

**Comment by ckoopmann** [comment]
Just noticed that the capitalization / casing in the burn category labels might be wrong / inconsistent with the rest of the app. ("Contract Creations" being and "Misc" being upper case)
Wasn't sure though. Mostly everything except names and abbrevations is lower case.
But then for example the "Gaming" category was upper case also, lmk what you think:
image

**Comment by JustinDrake** [comment]
+1 on making capitalisation consistent

**Comment by ckoopmann** [comment]
> +1 on making capitalisation consistent

Made the new / changed labels (Misc / Contract creations) consistent with the existing one in terms of captializing the first letter only:
image

**Pull request merged**
