### PR TITLE
Change fade-out timing for the top navigation and the four widgets

### PR DESCRIPTION
**Pull request by OlegLomaka**
[Trello card](https://trello.com/c/FOLG6w9Q/91-change-fade-out-timing-for-the-top-navigation-and-the-four-widgets)

Change point of hidden widgets, remove unnecessary code

### CODE REVIEW

**Comment by alextes** [comment]
@OlegLomaka yea using `document.querySelector` on scroll doesn't sound like a great idea 😅 , but then really it all depends on what the actual performance is whether I care or not.

It could be nice to use a ref, through react context or otherwise maybe? but again, only if it improves performance or enables server-side rendering or something. Otherwise, ¯\_(ツ)_/¯ .

**Comment by OlegLomaka** [comment]
@alextes Ok, i will try to edit this, and gonna use useRef for that

**Comment by alextes** [comment]
@OlegLomaka neat, if you want to look at it together at any point just lmk and we can hop on a video call but guessing you got this 💪 .

**Review by alextes — APPROVED** [review]
Looks great, code and in the browser 👍

**Pull request merged**
